// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr82BaSYNY_NHjxwNihQEHrvk8FppJ6Ew',
    appId: '1:498785682594:web:ea3dc2fdec3df0eb5a03fb',
    messagingSenderId: '498785682594',
    projectId: 'balaji-imitation',
    authDomain: 'balaji-imitation.firebaseapp.com',
    storageBucket: 'balaji-imitation.firebasestorage.app',
    measurementId: 'G-BS1QT29NZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq93HMIzzYtFF-8YZrcJ-KwvKYwiT3U5g',
    appId: '1:498785682594:android:70203e60de619ab05a03fb',
    messagingSenderId: '498785682594',
    projectId: 'balaji-imitation',
    storageBucket: 'balaji-imitation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPl6vPAAMmn0MwsWKasZUou9dFwNj9hGI',
    appId: '1:498785682594:ios:8beff3addec0e98d5a03fb',
    messagingSenderId: '498785682594',
    projectId: 'balaji-imitation',
    storageBucket: 'balaji-imitation.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPl6vPAAMmn0MwsWKasZUou9dFwNj9hGI',
    appId: '1:498785682594:ios:8beff3addec0e98d5a03fb',
    messagingSenderId: '498785682594',
    projectId: 'balaji-imitation',
    storageBucket: 'balaji-imitation.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr82BaSYNY_NHjxwNihQEHrvk8FppJ6Ew',
    appId: '1:498785682594:web:4df56a78ee5cc6de5a03fb',
    messagingSenderId: '498785682594',
    projectId: 'balaji-imitation',
    authDomain: 'balaji-imitation.firebaseapp.com',
    storageBucket: 'balaji-imitation.firebasestorage.app',
    measurementId: 'G-JVD0LTRDE4',
  );
}
